package escom.app_euclides.src.views;

import escom.app_euclides.src.components.ImageLoader;
import javax.swing.Icon;

public class MainView extends javax.swing.JFrame {
  private static MainView instance;
  private static String pathBG = "/BackgroundMain.jpg";
  
  private MainView() {
    initComponents();
    setLocationRelativeTo(null);
    setupBackground();
  }
  
  public static MainView getInstanceMain () {
    if (instance == null) {
      instance = new MainView();
    }
    return instance;
  }
  
  private void setupBackground () {
    Icon icon = ImageLoader.loadImage(pathBG, this.getWidth(), this.getHeight());
    this.LabelBackground.setIcon(icon);
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelTitle = new javax.swing.JLabel();
    btnStart = new javax.swing.JButton();
    LabelBackground = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    labelTitle.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 36)); // NOI18N
    labelTitle.setForeground(new java.awt.Color(255, 255, 255));
    labelTitle.setText("Affine Cipher");
    labelTitle.setPreferredSize(new java.awt.Dimension(200, 50));
    getContentPane().add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 300, -1));

    btnStart.setBackground(new java.awt.Color(37, 37, 37));
    btnStart.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
    btnStart.setText("Iniciar");
    btnStart.setPreferredSize(new java.awt.Dimension(100, 100));
    btnStart.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnStartActionPerformed(evt);
      }
    });
    getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 398, 158, 50));
    getContentPane().add(LabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 578, 600));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
    AEEView aeeView = AEEView.getInstanceAEEView();
    this.setVisible(false);
    aeeView.setVisible(true);
  }//GEN-LAST:event_btnStartActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel LabelBackground;
  private javax.swing.JButton btnStart;
  private javax.swing.JLabel labelTitle;
  // End of variables declaration//GEN-END:variables
}
